### ISSUE TITLE
libcpath_path.c: using NULL pointer

### ISSUE THREAD

**Issue by thims** [libyal/libcpath#1]
It's current_directory. For example, line 1002 checks "if( ( current_directory != NULL )". So... it looks like it can be NULL. But above this code you'll find many uses of current_directory.

Same with line 3993 and above.

**Comment by joachimmetz** [comment]
> But above this code you'll find many uses of current_directory.

Yes hence the check at: https://github.com/libyal/libcpath/blob/master/libcpath/libcpath_path.c#L898
